name: Build and test

on:
  push:
    branches: master

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          add-apt-repository ppa:neovim-ppa/unstable\
          && curl -sL https://deb.nodesource.com/setup_16.x | bash\
          && apt install -y\
            composer\
            gcc\
            g++\
            git\
            lua5.3\
            make\
            neovim\
            nodejs\
            php\
            php-dom\
            php-mbstring\
            python3\
            python3-pip\
            unzip\
            xclip\
            xfonts-utils\
            yarn
