---
name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Install Node
        run: |
          curl -sL https://deb.nodesource.com/setup_16.x | sudo bash\
          && sudo apt install -y nodejs

      - name: Install PHP
        run: |
          sudo apt update\
          && sudo apt install -y\
            php-8.1\
            php-8.1-dom\
            php-8.1-mbstring

      - name: Install Dependencies
        run: |
          sudo apt update\
          && sudo apt install -y\
            gcc\
            g++\
            git\
            lua5.3\
            make\
            unzip\
            xclip\
            xfonts-utils\
            nodejs\
            php\
            php-dom\
            php-mbstring\
            python3\
            python3-pip

      - name: Install Neovim nightly
        run: |
          sudo add-apt-repository ppa:neovim-ppa/unstable\
          && sudo apt update\
          && sudo apt install -y neovim
