---
name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: mbstring, dom

      - name: Install Dependencies
        run: |
          sudo apt update\
          && sudo apt install -y\
            gcc\
            g++\
            git\
            lua5.3\
            make\
            unzip\
            xclip\
            xfonts-utils\
            nodejs\
            python3\
            python3-pip

      - name: Install Neovim nightly
        run: |
          sudo add-apt-repository ppa:neovim-ppa/unstable\
          && sudo apt update\
          && sudo apt install -y neovim
