---
name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Install Neovim nightly
        run: |
          sudo add-apt-repository ppa:neovim-ppa/unstable\
          && sudo apt update\
          && sudo apt install -y neovim

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install neovim npm package
        run: sudo npm install -g neovim

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: mbstring, dom

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install pynvim python package
      - run: python -m pip install --user --upgrade pynvim 

      - name: Install Dependencies
        run: |
          sudo apt update\
          && sudo apt install -y\
            gcc\
            g++\
            git\
            lua5.3\
            make\
            unzip\
            xclip\
            xfonts-utils

